// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj7McZi-TGK82j56bvtvIwzkyIgwjGKhk',
    appId: '1:986128902130:web:4b848102cec6d1e2b6ad6b',
    messagingSenderId: '986128902130',
    projectId: 'pharma-96d2f',
    authDomain: 'pharma-96d2f.firebaseapp.com',
    storageBucket: 'pharma-96d2f.appspot.com',
    measurementId: 'G-X42BEZ4QGX',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj7McZi-TGK82j56bvtvIwzkyIgwjGKhk',
    appId: '1:986128902130:web:4b848102cec6d1e2b6ad6b',
    messagingSenderId: '986128902130',
    projectId: 'pharma-96d2f',
    authDomain: 'pharma-96d2f.firebaseapp.com',
    storageBucket: 'pharma-96d2f.appspot.com',
    measurementId: 'G-X42BEZ4QGX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkpJeh2nvSPbFlf5FjVmXm2VUrkkt9WpE',
    appId: '1:986128902130:ios:80a27afa0a789aefb6ad6b',
    messagingSenderId: '986128902130',
    projectId: 'pharma-96d2f',
    storageBucket: 'pharma-96d2f.appspot.com',
    iosBundleId: 'com.example.pharma',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkpJeh2nvSPbFlf5FjVmXm2VUrkkt9WpE',
    appId: '1:986128902130:ios:80a27afa0a789aefb6ad6b',
    messagingSenderId: '986128902130',
    projectId: 'pharma-96d2f',
    storageBucket: 'pharma-96d2f.appspot.com',
    iosBundleId: 'com.example.pharma',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKceb0-MIA2154JeLT1GlKagzo3Ghohos',
    appId: '1:986128902130:android:ff474c44cce6012db6ad6b',
    messagingSenderId: '986128902130',
    projectId: 'pharma-96d2f',
    storageBucket: 'pharma-96d2f.appspot.com',
  );

}